export let productsData;

productsData = [
    {   id:1,
        image:"https://www.redwolf.in/image/cache/catalog/sweatshirts/spider-man-logo-hoodie-india-700x700.jpg",
        name:"Chromozome",
        category:"hoodie",
        color:"Pink",
        size:"XL",
        inStock:true,
        price:"35.00"
    },
    {   id:2,
        image:"https://m.media-amazon.com/images/I/71R992flHhL._AC_UL480_FMwebp_QL65_.jpg",
        name:"MARK LOUIIS",
        category:"shirt",
        color:"Red",
        size:"XL",
        inStock:false,
        price:"23.00"
    },
    {   id:3,
        image:"https://m.media-amazon.com/images/I/618Wek95laS._AC_UL480_FMwebp_QL65_.jpg",
        name:"LAWMAN PG3",
        category:"shirt",
        color:"Red",
        size:"XL",
        inStock:true,
        price:"29.00"
    },
    {   id:4,
        image:"https://m.media-amazon.com/images/I/31SkJCDiHGL.jpg",
        name:"ENDEAVOUR WEAR",
        category:"trackpants",
        color:"Blue",
        size:"L",
        inStock:false,
        price:"40.00"
    },
    {   id:5,
        image:"https://m.media-amazon.com/images/I/71wIFf8FDVL._AC_UL480_FMwebp_QL65_.jpg",
        name:"SWADESI STUFF",
        category:"hoodie",
        color:"Blue",
        size:"L",
        inStock:true,
        price:"20.00"
    },
    {   id:6,
        image:"https://m.media-amazon.com/images/I/6113wVBRBoL._AC_UL480_FMwebp_QL65_.jpg",
        name:"JUGULAR",
        category:"hoodie",
        color:"Red",
        size:"XL",
        inStock:true,
        price:"30.00"
    },
    {   id:7,
        image:"https://m.media-amazon.com/images/I/71pt6DwRBIL._AC_UL480_FMwebp_QL65_.jpg",
        name:"Peppyzone",
        category:"trackpants",
        color:"Blue",
        size:"S",
        inStock:true,
        price:"33.00"
    },
    {   id:8,
        image:"https://m.media-amazon.com/images/I/61R11o1DC+S._AC_UL480_FMwebp_QL65_.jpg",
        name:"Puma",
        category:"trackpants",
        color:"White",
        size:"XL",
        inStock:true,
        price:"30.00"
    },
    {   id:9,
        image:"https://m.media-amazon.com/images/I/61L903jSl5L._AC_UL480_FMwebp_QL65_.jpg",
        name:"Jockey",
        category:"hoodie",
        color:"Pink",
        size:"S",
        inStock:true,
        price:"50.00"
    },
    {   id:10,
        image:"https://m.media-amazon.com/images/I/31EIw7nRkJL._AC_UL480_FMwebp_QL65_.jpg",
        name:"FLEXIMAA",
        category:"hoodie",
        color:"Pink",
        size:"S",
        inStock:true,
        price:"35.00"
    },
    {   id:11,
        image:"https://m.media-amazon.com/images/I/61EI0TrZHDL._AC_UL480_FMwebp_QL65_.jpg",
        name:"ALMO",
        category:"trackpants",
        color:"Pink",
        size:"S",
        inStock:true,
        price:"44.00"
    },
    {   id:12,
        image:"https://m.media-amazon.com/images/I/51W0YDiJobL._AC_UL480_FMwebp_QL65_.jpg",
        name:"ADRO",
        category:"hoodie",
        color:"Pink",
        size:"S",
        inStock:true,
        price:"61.00"
    },
    {   id:13,
        image:"https://m.media-amazon.com/images/I/71VqGO7q0OL._AC_UL480_FMwebp_QL65_.jpg",
        name:"Alan Jones Clothing",
        category:"trackpants",
        color:"Red",
        size:"L",
        inStock:true,
        price:"50.00"
    },
    {   id:14,
        image:"https://m.media-amazon.com/images/I/61bM2uv0ylL._AC_UL480_FMwebp_QL65_.jpg",
        name:"More & More",
        category:"shirt",
        color:"Pink",
        size:"S",
        inStock:true,
        price:"57.00"
    },
    {   id:15,
        image:"https://m.media-amazon.com/images/I/71mNefE3H9L._AC_UL480_FMwebp_QL65_.jpg",
        name:"Dagcros",
        category:"shirt",
        color:"White",
        size:"L",
        inStock:true,
        price:"77.00"
    },
    {   id:16,
        image:"https://m.media-amazon.com/images/I/610BjJqZ67L._AC_UL480_FMwebp_QL65_.jpg",
        name:"BAGHADBILLO",
        category:"trackpants",
        color:"Blue",
        size:"L",
        inStock:true,
        price:"24.00"
    },
    {   id:17,
        image:"https://m.media-amazon.com/images/I/71Cc3Ed35QL._AC_UL480_FMwebp_QL65_.jpg",
        name:"Alan Jones Clothing",
        category:"trackpants",
        color:"Green",
        size:"L",
        inStock:true,
        price:"50.00"
    },
    {   id:18,
        image:"https://m.media-amazon.com/images/I/71b4lp2YjiS._AC_UL480_FMwebp_QL65_.jpg",
        name:"EYEBOGLER",
        category:"shirt",
        color:"Blue",
        size:"L",
        inStock:true,
        price:"20.00"
    },
    {   id:19,
        image:"https://m.media-amazon.com/images/I/413h-VNE6oL._AC_UL480_FMwebp_QL65_.jpg",
        name:"Generic",
        category:"trackpants",
        color:"Pink",
        size:"S",
        inStock:true,
        price:"29.00"
    },
    {   id:20,
        image:"https://m.media-amazon.com/images/I/51WGD6pdHGL._AC_UL480_FMwebp_QL65_.jpg",
        name:"VETUE",
        category:"hoodie",
        color:"Pink",
        size:"S",
        inStock:true,
        price:"27.00"
    },
    {   id:21,
        image:"https://m.media-amazon.com/images/I/71isliRHNfL._AC_UL480_FMwebp_QL65_.jpg",
        name:"ADBUCKS",
        category:"shirt",
        color:"Pink",
        size:"S",
        inStock:true,
        price:"34.00"
    },
    {   id:22,
        image:"https://m.media-amazon.com/images/I/814iZVTFoZL._AC_UL480_FMwebp_QL65_.jpg",
        name:"ADRO",
        category:"shirt",
        color:"Pink",
        size:"S",
        inStock:true,
        price:"33.00"
    },
]